### PR TITLE
Janky 2

### PR DESCRIPTION
**Pull request by sj213**
Brought the NEMO-cloud CM up-to-date. The most important change is the value for `vm_prefix` (that value has changed to clearly distinguish NEMO from bwCloud VMs). The rest is mostly cleanup and housekeeping. The NEMO-CM image now also has a Q&D JSON-pretty-printer in `/opt/bin`, for inspecting the machine registry.

_This PR does not affect the bwCloud setup._

Ping @bgruening @erasche

### CODE REVIEW

**Comment by erasche** [comment]
> Q&D JSON-pretty-printer

you might consider `jq` in the future. I know @bgruening and I are very fond of it. By default it pretty prints the input, but it also lets you do some very complex filtering on-the-fly.

This all looks great though! Super happy to get the old tarballs cleaned up!

**Comment by bgruening** [comment]
👍 to `jq` you will love it :)

**Comment by sj213** [comment]
Thx for the tip; so someone has written an equivalent of XSLT for JSON after all. Might come in handy sometime. (Though the filter language is probably way too complex to memorize its syntax unless you use it regularly; XPath on steroids as it were. I guess the only filter that casual users will ever use is `'.'`)

**Comment by erasche** [comment]
Yep, exactly like xslt. Ah how I miss xslt.

oh yeah, it's a huge language, I use like 1% to select out some data and maybe ` | @tsv` with the `-r` flag which converts a array of arrays into a tabular file.

**Comment by sj213** [comment]
Yes, XSLT is powerful and the model behind it is not too bad (considering it is based on XML that is...)

(Whenever I see anything based on XML my first thought is: "So this was done by the same sort of people who always complain that Lisp is supposedly unreadable XD")

http://homepages.inf.ed.ac.uk/wadler/language.pdf
http://homepages.inf.ed.ac.uk/wadler/papers/xml-essence/xml-essence.pdf

**Pull request merged**
